wget http://www.drive5.com/muscle/downloads3.8.31/muscle3.8.31_src.tar.gz
  546  tar zxvf muscle3.8.31_src.tar.gz 
  547  cd muscle3.8.31
  548  ls
  549  cd src/
  550  ls
  551  less README.txt 
  552  less Makefile 
  553  make


