; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using the MEGA Prototyper.
[ MEGAinfo ]
ver                                  = 10180514-x86_64 Debian               
[ DataSettings ]
datatype                             = snNucleotide                        
containsCodingNuc                    = True                                
MissingBaseSymbol                    = ?                                   
IdenticalBaseSymbol                  = .                                   
GapSymbol                            = -                                   
[ ProcessTypes ]
ppInfer                              = true                                
ppML                                 = true                                
[ AnalysisSettings ]
Analysis                             = Phylogeny Reconstruction            
Statistical Method                   = Maximum Likelihood                  
Phylogeny Test                       = ====================                
Test of Phylogeny                    = Bootstrap method                    
No. of Bootstrap Replications        = 500                                 
Substitution Model                   = ====================                
Substitutions Type                   = Nucleotide                          
Model/Method                         = Kimura 2-parameter model            
Rates and Patterns                   = ====================                
Rates among Sites                    = Uniform Rates                       
No of Discrete Gamma Categories      = Not Applicable                      
Data Subset to Use                   = ====================                
Gaps/Missing Data Treatment          = Complete deletion                   
Site Coverage Cutoff (%)             = Not Applicable                      
Select Codon Positions               = 1st, 2nd, 3rd, Non-Coding           
Tree Inference Options               = ====================                
ML Heuristic Method                  = Nearest-Neighbor-Interchange (NNI)  
Initial Tree for ML                  = Make initial tree automatically (Neighbor Joining)
Branch Swap Filter                   = Strong                              
System Resource Usage                = ====================                
Number of Threads                    = 1                                   
Genetic Code Table                   = Not Applicable                      
Genetic Code                         = Not Applicable                      
Has Time Limit                       = False                               
Maximum Execution Time               = -1  

